version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app:latest
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/app
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
